---
title: Why this field is missing?
author: Li Wang
date: '2018-09-12'
slug: why-this-field-is-missing
categories:
  - data analysis
tags:
  - missing data
---

One of the daily challenge for someone who works with data is missing data. After a few years working with historical data (which means it is not captured for your analysis), I noticed that data was seldom missing at random and understanding how/why it is missing could be very important for the analysis (especially when your analysis would have significant impact and needs to be carefully validated).

Before I go into the details, I would say my experiences are based on insurance pricing, namely, how to come up with appropriate price for a given risk. For example, when you quote for a personal auto policy, the prcing model should adequately give some discount for positive traits and experiences (safe driver, no moving violation etc.) and surcharge for other less desirable traits (young male driver with a fancy sports car). As insurance pricing is heavily regulated in US at state level, the final pricing model needs to be filed to state regulators (for example, in Massachusetts, [division of insurance](https://www.mass.gov/orgs/division-of-insurance)) and sometimes available to public. Obviously, the final model needs to be reasonable even to people who is not familiar with statistics. The need for interpretability and obvious dollar impact of the models (if your model is less accurate compared to competitors, you will get [adverse selected](https://en.wikipedia.org/wiki/Adverse_selection#Insurance)) would mean the data scientists need to understand all parts of their models and are able to explain them. Combined with the nature of our data(historical and often human input), it leads to many rabbit holes that I would try to summarize here. 



